version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm i

      - run:
          name: Build
          command: echo "build"

      - run:
          name: Login To Monaca
          command: echo $MONACA_PASSWORD | npx monaca login $MONACA_EMAIL

      - run:
          name: Upload to Monaca Cloud
          command: npx monaca upload --force

      - run:
          name: Build Android (Debug)
          command: npx monaca remote build android --skipUpload --build-type=debug --output "./android-debug-build.apk";

      - run:
          name: List Project Files
          command: ls -la;

      - store_artifacts:
          path: android-debug-build.apk